### ISSUE TITLE
Simultaneous rolls

### ISSUE THREAD

**Issue by seansps** [3d-dice/dice-box-threejs#10]
How hard would it be to make an update that allows for simultaneous rolls? Currently, even if you use the "add" method, it interrupts the ongoing animation.

**Comment by frankieali** [comment]
Simultaneous rolls are a limit of this library because it break determinism. What's happening is on a roll the physics are calculated within a few milliseconds (simulation mode) to determine the final dice outcome. The dice faces are then swapped on the 3D models so the desired face will be face up at the end. Finally, the physics are run again (with the same starting inputs leading to the same final outcome) this time while rendering the dice. Adding dice dynamically to the roll would interfere with the physics calculations and change the final outcomes. 
Adding dice dynamically could be done, but it would sacrifice pre-deterministic outcomes, which is the main feature of this library.
My other [dice-box](https://github.com/3d-dice/dice-box) project does allow for adding dice dynamically. It uses the BabylonJS rendering engine instead of ThreeJS. It does not have determinism and was designed to be as random as possible.

**Comment by spschnell** [comment]
Thanks for the response! That makes a lot of sense. I suppose what I can do is render multiple instances and manage a queue for each, to allow for a certain number of rolls per instance at a time.

**Comment by seansps** [comment]
> Simultaneous rolls are a limit of this library because it break determinism. What's happening is on a roll the physics are calculated within a few milliseconds (simulation mode) to determine the final dice outcome. The dice faces are then swapped on the 3D models so the desired face will be face up at the end. Finally, the physics are run again (with the same starting inputs leading to the same final outcome) this time while rendering the dice. Adding dice dynamically to the roll would interfere with the physics calculations and change the final outcomes. Adding dice dynamically could be done, but it would sacrifice pre-deterministic outcomes, which is the main feature of this library. My other [dice-box](https://github.com/3d-dice/dice-box) project does allow for adding dice dynamically. It uses the BabylonJS rendering engine instead of ThreeJS. It does not have determinism and was designed to be as random as possible.

Thanks for the detailed response! I suppose what I could do instance is manage multiple instances with a queue and then that would allow for a certain number of simultaneous rolls. The physics would not interact, but that's probably fine.
